#! /bin/sh

#Launcher
$HOME/.config/bspwm/scripts/autostart.sh

#Monitor
 if [[ $(hostname) == 'sean-pavilion' ]]; then
   if xrandr | grep "HDMI-0 disconnected"; then
     bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
   else
     bspc monitor eDP-1-1 -d I III V VII IX 
     bspc monitor HDMI-0 -d II IV VI VIII X
   fi  
 elif [[ $(hostname) == 'sean-desktop' ]]; then
     bspc monitor DVI-I-1 -d I III V VII IX
     bspc monitor VGA-1 -d II IV VI VIII X
 fi
 
#BSPWM configuration
bspc config border_width         1
bspc config window_gap           32 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#282828"
bspc config active_border_color		"#1d2021"
bspc config focused_border_color	"#689d6a"
bspc config presel_feedback_color	"#a89984"
bspc config urgent_border_color "#cc241d"

#Fullscreen applications
bspc rule -a Gimp state=fullscreen

#Floating applications
bspc rule -a feh state=floating
bspc rule -a mpv state=floating sticky=on
bspc rule -a Gnome-calculator state=floating
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Lxappearance state=floating
bspc rule -a Nitrogen state=floating sticky=on
bspc rule -a Pavucontrol state=floating
bspc rule -a Fcitx-config-gtk3 state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a scrcpy state=floating
